# Application configuration for VoIP AI Agent
# Use this file for paths, API keys (if not in .env), and other settings.

# Example structure:
# stt:
#   google_cloud_credentials_path: /path/to/your/google_cloud_key.json
# nlp:
#   model_path: /data/voip-ai-agent/models/nlp/llama4_scout
#   fine_tuned_dataset: /data/voip-ai-agent/data/processed/vietnamese_cskh_dataset.json
# tts:
#   model_path: /data/voip-ai-agent/models/tts/indic_parler_tts
# asterisk:
#   agi_port: 4573
#   ari_url: http://localhost:8088
#   ari_username: asterisk
#   ari_password: mysecret
# crm:
#   type: zoho
#   api_key: your_zoho_api_key
#   base_url: https://www.zohoapis.com

# ARI Configuration (loaded from .env)
ari:
  url: ${ARI_URL:-http://localhost:8088/}
  username: ${ARI_USERNAME:-asterisk}
  password: ${ARI_PASSWORD:-asterisk}
  app_name: ${ARI_APP_NAME:-voip-ai-agent}

# Cấu hình Speech Adaptation để cải thiện độ chính xác của STT
speech_adaptation:
  default:
    # Các cụm từ cần gợi ý cho STT để tăng độ chính xác
    # Ví dụ: tên công ty, tên sản phẩm, thuật ngữ chuyên ngành
    phrase_hints:
      - "tổng đài AI"
      - "công ty Viễn Thông A"
      - "sản phẩm Bphone"
      - "gói cước SuperNet"
    # Mức độ ưu tiên cho các cụm từ gợi ý (từ 1.0 đến 20.0)
    boost: 15.0
    # Bật/tắt tự động thêm dấu câu
    enable_automatic_punctuation: true

  # Bạn có thể thêm các context khác ở đây, ví dụ:
  # sales_campaign_q1:
  #   phrase_hints: ["khuyến mãi", "giảm giá", "miễn phí vận chuyển"]
  #   boost: 12.0
  #   enable_automatic_punctuation: true

# Cấu hình Text-to-Speech (TTS)
tts:
  # Giọng nói mặc định sẽ được sử dụng nếu không có chỉ định nào khác
  default_voice: "female_a"
  
  # Thư mục để lưu các file audio đã được cache
  # Đảm bảo thư mục này tồn tại và Asterisk có quyền ghi vào
  cache_dir: "/tmp/tts_cache"
  
  # Tốc độ nói mặc định (1.0 là bình thường)
  speaking_rate: 1.0
  
  # Danh sách các giọng nói có sẵn
  voices:
    female_a: "vi-VN-Wavenet-A"
    male_b: "vi-VN-Wavenet-B"
    female_c: "vi-VN-Wavenet-C"
    male_d: "vi-VN-Wavenet-D"
