# Application configuration for VoIP AI Agent
# Use this file for paths, API keys (if not in .env), and other settings.

# ARI Configuration (loaded from .env)
ari:
  url: ${ARI_URL:-http://localhost:8088/}
  username: ${ARI_USERNAME:-asterisk}
  password: ${ARI_PASSWORD}
  app_name: ${ARI_APP_NAME:-voip-ai-agent}

# Cấu hình Speech Adaptation để cải thiện độ chính xác của STT
speech_adaptation:
  default:
    phrase_hints:
      - "tổng đài AI"
      - "công ty Viễn Thông A"
      - "sản phẩm Bphone"
      - "gói cước SuperNet"
    boost: 15.0
    enable_automatic_punctuation: true



# Cấu hình Natural Language Processing (NLP)
nlp:
  # Backend để xử lý NLP. Hiện tại chỉ có model cho unsloth_transformers.
  backend: unsloth_transformers
  
  # Đường dẫn đến model Hugging Face đã được xác minh.
  model_path: /data/voip-ai-agent/models/nlp/llama4_scout
  
  # Đường dẫn GGUF (chưa có file) - để tham khảo cho tương lai.
  gguf_path: /data/voip-ai-agent/models/nlp/Llama-4-Scout-17B-16E-Instruct.Q4_K_M.gguf
  
  # Các tham số cho việc sinh văn bản
  max_new_tokens: 128
  temperature: 0.6
  top_p: 0.9
  stop: ["</s>", "###", "Human:", "Assistant:"]
